name: Words by Sørensen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.76227
title: Words by Sørensen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#304a4c'
    - '#c4c5c7'
    - '#fcfefd'
    - '#b65e4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
