name: Words by Sørensen
favicon: null
layout_spectrum: 0.6582980202510953
typography_spectrum: 0.2842168412171304
title: Words by Sørensen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#4e5662'
    - '#cfd6dd'
    - '#252a2e'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.16128307511098683
purpose: []
